development:
  host: 127.0.0.1
  port: 6379

staging:
  host: <%= ENV['ROLLOUT_REDIS_HOST'] %>
  port: <%= ENV['ROLLOUT_REDIS_PORT'] %>


production:
  host: <%= ENV['ROLLOUT_REDIS_HOST'] %>
  port: <%= ENV['ROLLOUT_REDIS_PORT'] %>

  